# Generated by Django 4.2 on 2023-04-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_descripción_atributos_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atributos',
            name='booleano',
        ),
        migrations.AlterField(
            model_name='atributos',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
